### ISSUE TITLE
MD5 CSR signing will no longer work

### ISSUE THREAD

**Issue by willfurnell** [sfayer/cert_sorcerer#7]
Hi,
A change on the CA backend means that MD5 signing of CSRs will soon no longer be supported. You should be able to change this to something like SHA256withRSA (this is what CertWizard is now using) for continued support for CSRs,
Thanks,
Will.

https://github.com/sfayer/cert_sorcerer/blob/02d41bc68510b964be42a6c5917066b2920992f4/CS.py30#L318

**Comment by sfayer** [comment]
Thanks, I've updated it to use sha256 in the latest tagged version (1.0.10).

Regards,
Simon
